// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLp9hgyelsRqnZ8zorTqClk4yXvH8FmOo',
    appId: '1:308136893321:web:7e25b4e0119b50af9ddf58',
    messagingSenderId: '308136893321',
    projectId: 'cmsc128-rabbithole',
    authDomain: 'cmsc128-rabbithole.firebaseapp.com',
    storageBucket: 'cmsc128-rabbithole.appspot.com',
    measurementId: 'G-P6LNMLH6G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP216IeuSqcOufXqDIn-pibmOo93MVr6E',
    appId: '1:308136893321:android:515f6b044917f3ba9ddf58',
    messagingSenderId: '308136893321',
    projectId: 'cmsc128-rabbithole',
    storageBucket: 'cmsc128-rabbithole.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNRlS8FV6rhqDK8kBN_KUgfBIyV-4F5DE',
    appId: '1:308136893321:ios:171f8b9e380518f19ddf58',
    messagingSenderId: '308136893321',
    projectId: 'cmsc128-rabbithole',
    storageBucket: 'cmsc128-rabbithole.appspot.com',
    iosBundleId: 'com.example.cmsc128Lab',
  );
}
